// Dependency-free regression tests executing the production inline script in a VM.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {createHash}=require('node:crypto');
const html=fs.readFileSync(process.env.RANKING_HTML||'face-ranking/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const KEY='zaka-face-ranking-v1';
const draft={v:1,t:'自分の下書き',m:[['井上和','n']]};
const shared={v:1,t:'友達の選抜',m:[['小川彩','n']]};
const fragment=s=>'#s='+Buffer.from(JSON.stringify(s)).toString('base64url');
function app({seed=draft,hash='',blocked=false}={}){
 const elements=new Map(),storage=new Map(seed?[[KEY,JSON.stringify(seed)]]:[]),drawn=[],listeners={};let blobs=0,modalCount=0;
 class Element{constructor(){this.value='';this.textContent='';this.children=[];this.dataset={};this.style={};this.attributes={};this.classList={contains:()=>false};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}querySelector(){return null;}focus(){}select(){}showModal(){this.open=true;modalCount++;}close(){this.open=false;}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
 const ctx=new Proxy({fillText:text=>drawn.push(text),measureText:t=>({width:t.length*12})},{get:(o,k)=>k in o?o[k]:()=>{}});
 const sandbox={console,TextEncoder,TextDecoder,Uint8Array,setTimeout:()=>0,clearTimeout:()=>{},atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),confirm:()=>true,location:{hash,origin:'https://test.invalid',pathname:'/face-ranking/'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('disabled');storage.set(k,v);}},URL:{createObjectURL:()=> 'blob:export',revokeObjectURL:()=>{}},File:class{constructor(parts,name,options){Object.assign(this,{parts,name,...options});}},navigator:{canShare:()=>true,share:async data=>{sandbox.shareData=data;}},document:{getElementById:get,querySelectorAll:()=>[],fonts:{ready:Promise.resolve()},createElement:tag=>{const el=new Element();if(tag==='canvas'){el.getContext=()=>ctx;el.toBlob=cb=>{blobs++;sandbox.blobCallback=cb;if(!sandbox.delayBlob)cb(sandbox.failBlob?null:{png:true});};}return el;}},window:{addEventListener:(event,fn)=>listeners[event]=fn}};
 const context=vm.createContext(sandbox);vm.runInContext(script,context);
 return{get,storage,drawn,sandbox,run:code=>vm.runInContext(code,context),get blobs(){return blobs;},get modals(){return modalCount;},navigate:hash=>{sandbox.location.hash=hash;listeners.hashchange();}};
}
test('CSP hash matches exact production script',()=>{assert.ok(html.includes("script-src 'sha256-"+createHash('sha256').update(script).digest('base64')+"'"));new vm.Script(script);});
test('ranking uses exactly the source roster',()=>{const a=app();const original=fs.readFileSync('senbatsu/index.html','utf8').match(/const NAMES=(.*);/)[1];assert.equal(a.run('JSON.stringify(NAMES)'),JSON.stringify(vm.runInNewContext('('+original+')')));assert.equal(a.run('catalog.length'),92);});
test('add, duplicate prevention, move, remove and undo retain contiguous ranks',()=>{const a=app({seed:null});a.run("place(['井上和','n']);place(['小川彩','n']);place(['小川彩','n']);place(['遠藤さくら','n'])");assert.equal(a.run('filled()'),3);a.run('moveMember(2,0)');assert.equal(a.run('state.m[0][0]'),'遠藤さくら');a.run('removeMember(1)');assert.equal(a.run('filled()'),2);a.get('undo').onclick();assert.equal(a.run('filled()'),3);a.run('moveMember(-1,4);moveMember(0,36)');assert.equal(a.run('filled()'),3);});
test('36-member limit, validation rejects duplicates, invalid and overlong payloads',()=>{const a=app({seed:null});a.run('catalog.slice(0,37).forEach(place)');assert.equal(a.run('filled()'),36);for(const code of ["validate({v:1,t:'x',m:[['A','n'],['Ａ','n']]})","validate({v:1,t:'x',m:[['A','invalid']]})","validate({v:1,t:'x',m:catalog.slice(0,37)})","validate({v:2,t:'x',m:[]})","decode('a'.repeat(16001))"]){assert.throws(()=>a.run(code));}});
test('ranking writes never alter formation drafts, custom names or named saves',()=>{const a=app();for(const k of ['zaka-senbatsu-v1','zaka-senbatsu-v1-saved','zaka-senbatsu-v1-custom'])a.storage.set(k,'sentinel');a.run("place(['小川彩','n'])");a.get('save').onclick();for(const k of ['zaka-senbatsu-v1','zaka-senbatsu-v1-saved','zaka-senbatsu-v1-custom'])assert.equal(a.storage.get(k),'sentinel');assert.equal(JSON.parse(a.storage.get(KEY)).m.length,2);assert.equal(JSON.parse(a.storage.get(KEY+'-saved')).length,1);});
test('named save/load/delete and reset are guarded and undoable where promised',()=>{const a=app();a.get('save').onclick();const id=JSON.parse(a.storage.get(KEY+'-saved'))[0].id;a.get('saved').value=id;a.run("place(['小川彩','n'])");a.sandbox.confirm=()=>false;a.get('load').onclick();assert.equal(a.run('filled()'),2);a.get('reset').onclick();assert.equal(a.run('filled()'),2);a.get('delete').onclick();assert.equal(JSON.parse(a.storage.get(KEY+'-saved')).length,1);a.sandbox.confirm=()=>true;a.get('load').onclick();assert.equal(a.run('filled()'),1);a.get('undo').onclick();assert.equal(a.run('filled()'),2);a.get('reset').onclick();assert.equal(a.run('filled()'),0);a.get('undo').onclick();assert.equal(a.run('filled()'),2);a.get('delete').onclick();assert.equal(JSON.parse(a.storage.get(KEY+'-saved')).length,0);});
test('repeat share transitions restore local draft; malformed links preserve current state',()=>{const a=app();a.run("state.t='latest';persist()");for(const h of [fragment(shared),fragment({...shared,t:'second'}),'',fragment(shared),''])a.navigate(h);assert.equal(a.run('state.t'),'latest');a.navigate(fragment(shared));a.navigate('#s=invalid');a.run("state.t='shared edit';persist()");assert.equal(JSON.parse(a.storage.get(KEY)).t,'latest');a.navigate('');assert.equal(a.run('state.t'),'latest');assert.equal(a.run('history.length'),0);});
test('storage failure preserves in-memory draft through share navigation',()=>{const a=app({blocked:true});a.run("state.t='unsaved';persist()");a.navigate(fragment(shared));a.navigate('');assert.equal(a.run('state.t'),'unsaved');assert.equal(a.run('storageError'),true);});
test('Unicode title and names share round-trip safely; script-like text remains text',()=>{const a=app();a.run("state={v:1,t:'<img onerror=alert(1)>',m:[['<script>','x']]};render()");assert.equal(a.get('board-title').textContent,'<img onerror=alert(1)>');assert.equal(a.run('decode(encode(state)).m[0][0]'),'<script>');});
test('PNG snapshot survives font wait, rerender and repeated requests, native share uses snapshot title',async()=>{const a=app();let release;a.sandbox.document.fonts.ready=new Promise(r=>release=r);a.sandbox.delayBlob=true;const pending=a.run('makePNG()');assert.equal(a.get('png').attributes['aria-busy'],'true');a.run("state.t='edited';state.m=[['小川彩','n'],['遠藤さくら','n']];render()");assert.equal(a.get('png').disabled,true);await a.run('makePNG()');release();for(let i=0;i<10;i++)await Promise.resolve();assert.equal(a.blobs,1);assert.ok(a.drawn.includes(draft.t));assert.ok(a.drawn.includes('井上和'));assert.ok(a.drawn.includes('1人の、わたしだけのランキング'));assert.ok(!a.drawn.includes('小川彩'));a.sandbox.blobCallback({png:true});await pending;assert.equal(a.modals,1);assert.equal(a.get('png').attributes['aria-busy'],undefined);await a.get('share-image').onclick();assert.equal(a.sandbox.shareData.title,draft.t);});
test('PNG failure unlocks retry; repeated completion reuses open dialog; empty ranking exports nothing',async()=>{const a=app();a.sandbox.failBlob=true;await a.run('makePNG()');assert.equal(a.get('png').disabled,false);assert.match(a.get('toast').textContent,/作成できません/);a.sandbox.failBlob=false;await a.run('makePNG()');assert.equal(a.modals,1);await a.run('makePNG()');assert.equal(a.modals,1);const b=app({seed:null});await b.run('makePNG()');assert.equal(b.blobs,0);});
test('photo cap rejects a 37th mapping before decoding; malformed stored values are rejected',async()=>{const a=app();a.run("photos=Object.fromEntries(Array.from({length:36},(_,i)=>['n:test'+i,'data:image/jpeg;base64,AAAA']))");a.sandbox.file={type:'image/png',size:4};await a.run("importPhoto(file,'n:井上和')");assert.match(a.get('toast').textContent,/36人/);assert.equal(a.run('Object.keys(photos).length'),36);for(const value of ['https://example.com/photo.jpg','data:image/svg+xml;base64,AAAA','data:image/jpeg;base64,<script>','data:image/jpeg;base64,'+'A'.repeat(180000)]){a.sandbox.photoValue=value;assert.equal(a.run('validPhoto(photoValue)'),false);}});
