const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const {chromium,webkit}=require('playwright');
const KEY='zaka-face-ranking-v1',PHOTO=KEY+'-photos';
const draft={v:1,t:'わたしの好き顔ランキング',m:[['井上和','n'],['小川彩','n']]};
const hash=s=>'#s='+Buffer.from(JSON.stringify(s)).toString('base64url');
let browser,server,origin;
before(async()=>{server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(req.url.startsWith('/senbatsu')?'senbatsu/index.html':'face-ranking/index.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await (process.env.BROWSER==='webkit'?webkit:chromium).launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:process.env.BROWSER==='webkit'?[]:['--no-sandbox']});});
after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));});
async function pageFor(t,{photos={},seed=draft}={}){const context=await browser.newContext();t.after(()=>context.close());await context.addInitScript(({key,photos,seed})=>{if(!sessionStorage.seeded){if(seed)localStorage.setItem(key,JSON.stringify(seed));localStorage.setItem(key+'-photos',JSON.stringify(photos));localStorage.setItem('zaka-senbatsu-v1','sentinel');sessionStorage.seeded='yes';}},{key:KEY,photos,seed});const page=await context.newPage();const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))external.push(r.url());});t.after(()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});await page.goto(origin+'/face-ranking/');await page.locator('.rank-row').first().waitFor();return page;}
async function raster(page,type='image/png',color='red'){return Buffer.from(await page.evaluate(({type,color})=>{const c=document.createElement('canvas');c.width=20;c.height=30;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,20,30);return c.toDataURL(type).split(',')[1];},{type,color}),'base64');}
async function importFile(page,buffer,mimeType='image/png'){await page.locator('.rank-row [data-action=photo]').first().click();await page.locator('#photo-input').setInputFiles({name:'local-photo',mimeType,buffer});await page.waitForFunction(()=>!photoImporting);}
async function photo(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key))['n:井上和'],PHOTO);}
test('local JPEG/PNG/WebP import, replacement, reload, remove, clear and URL privacy',async t=>{const p=await pageFor(t);for(const format of ['image/png','image/jpeg','image/webp']){await importFile(p,await raster(p,format),format);assert.match(await photo(p),/^data:image\/jpeg;base64,/);assert.equal(await p.locator('.rank-row .avatar img').count(),1);}
const old=await photo(p);await importFile(p,await raster(p,'image/png','blue'));assert.notEqual(await photo(p),old);await p.reload();assert.equal(await p.locator('.rank-row .avatar img').count(),1);assert.equal(await p.evaluate(()=>decode(encode(state)).m.length),2);assert.ok(!(await p.evaluate(()=>shareURL())).includes('data:'));assert.equal(await p.evaluate(()=>localStorage.getItem('zaka-senbatsu-v1')),'sentinel');p.on('dialog',d=>d.accept());await p.locator('.rank-row [data-action=unphoto]').first().click();assert.equal(await photo(p),undefined);await importFile(p,await raster(p));await p.locator('#clear-photos').click();assert.equal(await p.evaluate(()=>Object.keys(photos).length),0);});
test('invalid MIME, signatures, damaged data, oversized input/pixels and cancelled picker',async t=>{const p=await pageFor(t);for(const [buffer,type] of [[Buffer.from('<svg/>'),'image/svg+xml'],[Buffer.from('not png'),'image/png'],[Buffer.from([137,80,78,71,13,10,26,10]),'image/png'],[Buffer.alloc(10*1024*1024+1),'image/jpeg']]){await importFile(p,buffer,type);assert.equal(await photo(p),undefined);}
await p.evaluate(async()=>{const original=loadImage;loadImage=async()=>({naturalWidth:6000,naturalHeight:6000});await importPhoto(new File([new Uint8Array([255,216,255])],'big.jpg',{type:'image/jpeg'}),'n:井上和');loadImage=original;});assert.equal(await photo(p),undefined);await p.locator('.rank-row [data-action=photo]').first().click();await p.locator('#photo-input').setInputFiles([]);assert.equal(await p.evaluate(()=>photoImporting),false);});
test('photo storage quota failure preserves old photo, reports failure, unlocks retry',async t=>{const p=await pageFor(t);await importFile(p,await raster(p));const old=await photo(p);await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.endsWith('-photos'))throw new DOMException('quota','QuotaExceededError');return originalSet.call(this,k,v);};});await importFile(p,await raster(p,'image/png','blue'));assert.equal(await photo(p),old);assert.match(await p.locator('#toast').textContent(),/保存できません/);await p.evaluate(()=>Storage.prototype.setItem=originalSet);await importFile(p,await raster(p,'image/png','blue'));assert.notEqual(await photo(p),old);});
test('corrupt stored photos are filtered and decode failure exports name fallback',async t=>{const p=await pageFor(t,{photos:{'bad:key':'data:image/jpeg;base64,AAAA','n:井上和':'garbage','n:小川彩':'data:image/jpeg;base64,AAAA'}});assert.equal(await p.evaluate(()=>Object.keys(photos).length),1);await p.locator('#png').click();await p.locator('#export-dialog[open]').waitFor();assert.match(await p.locator('#export-note').textContent(),/1人の写真/);});
test('pending import cannot survive remove/undo/load/hash/clear; repeat imports are guarded',async t=>{const p=await pageFor(t);const bytes=await raster(p);for(const operation of ['removeMember(0)','$('+'"undo").onclick()','$('+'"load").onclick()','location.hash='+JSON.stringify(hash({...draft,t:'共有'})),'$("clear-photos").onclick()']){await p.evaluate(()=>{state=JSON.parse(localStorage.getItem(KEY));render();history.push(clone(state));photos={'n:小川彩':'data:image/jpeg;base64,AAAA'};$('save').onclick();$('saved').value=savedItems()[0].id;window.confirm=()=>true;window.originalImage=loadImage;loadImage=()=>new Promise(r=>window.releaseImage=()=>r({naturalWidth:20,naturalHeight:30}));});await p.evaluate(buffer=>{window.pendingImport=importPhoto(new File([Uint8Array.from(buffer)],'x.png',{type:'image/png'}),'n:井上和');},Array.from(bytes));await p.waitForFunction(()=>!!window.releaseImage);await p.evaluate(async()=>{await importPhoto(new File(['x'],'x.png',{type:'image/png'}),'n:井上和');});await p.evaluate(operation=>{if(operation.startsWith('remove'))removeMember(0);else if(operation.includes('undo'))$('undo').onclick();else if(operation.includes('load'))$('load').onclick();else if(operation.startsWith('location'))location.hash='#s='+encode({...state,t:'shared'});else $('clear-photos').onclick();},operation);await p.waitForTimeout(40);await p.evaluate(async()=>{releaseImage();await pendingImport;loadImage=originalImage;window.releaseImage=null;});assert.equal(await p.evaluate(()=>photos['n:井上和']),undefined);await p.evaluate(()=>{location.hash='';});await p.waitForTimeout(40);}});
test('picker opened before navigation cannot attach to destination member',async t=>{const p=await pageFor(t);await p.locator('.rank-row [data-action=photo]').first().click();await p.evaluate(h=>location.hash=h,hash({...draft,t:'別画面'}));await p.waitForTimeout(40);await p.locator('#photo-input').setInputFiles({name:'x.png',mimeType:'image/png',buffer:await raster(p)});assert.equal(await photo(p),undefined);assert.match(await p.locator('#toast').textContent(),/中止/);});
test('PNG freezes photo/title across font wait, exports real pixels, repeats/failure recover',async t=>{const p=await pageFor(t);await importFile(p,await raster(p));await p.evaluate(()=>{Object.defineProperty(document.fonts,'ready',{value:new Promise(r=>window.releaseFonts=r),configurable:true});window.originalDraw=CanvasRenderingContext2D.prototype.drawImage;window.drawSources=[];CanvasRenderingContext2D.prototype.drawImage=function(img,...a){drawSources.push(img.src);return originalDraw.call(this,img,...a);};});const old=await photo(p);await p.locator('#png').click();await p.evaluate(()=>{photos={};state.t='changed';render();$('png').onclick();releaseFonts();});await p.locator('#export-dialog[open]').waitFor();assert.deepEqual(await p.evaluate(()=>drawSources),[old]);assert.deepEqual(await p.locator('#export-image').evaluate(async img=>{await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d');x.drawImage(img,0,0);const v=x.getImageData(180,240,1,1).data;return [img.naturalWidth,img.naturalHeight,...v];}),[1200,532,254,0,0,255]);fs.mkdirSync('test-results',{recursive:true});await p.locator('#export-image').evaluate(async img=>{window.pngBytes=Array.from(new Uint8Array(await exportBlob.arrayBuffer()));});fs.writeFileSync('test-results/face-ranking-photo.png',Buffer.from(await p.evaluate(()=>pngBytes)));await p.keyboard.press('Escape');await p.evaluate(()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){HTMLCanvasElement.prototype.toBlob=original;cb(null);};});await p.locator('#png').click();await p.waitForFunction(()=>!exporting);assert.match(await p.locator('#toast').textContent(),/作成できません/);await p.locator('#png').click();await p.locator('#export-dialog[open]').waitFor();});
test('36 ranks, long names/title, responsive layout, search, keyboard focus and dialogs',async t=>{const p=await pageFor(t);await p.evaluate(()=>{state.m=catalog.slice(0,35).concat([['非常に長いカスタムメンバーの名前','x']]);state.t='長いタイトル'.repeat(6);render();});for(const width of [320,390,1440]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);fs.mkdirSync('test-results',{recursive:true});await p.screenshot({path:'test-results/face-ranking-'+width+'.png',fullPage:false});}
await p.locator('.rank-row').nth(1).locator('[data-action=up]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'undo');await p.locator('.rank-row').nth(1).locator('[data-action=remove]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'undo');await p.locator('#search').fill('小川');assert.equal(await p.locator('.member').count(),1);await p.locator('#share').click();await p.keyboard.press('Escape');await p.locator('#link-dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement.id==='share');assert.equal(await p.evaluate(()=>document.activeElement.id),'share');await p.locator('#share').click();await p.locator('#link-dialog[open]').waitFor();});
test('share back/forward preserves local draft and rejects unapproved scripts',async t=>{const p=await pageFor(t);await p.locator('#title').fill('ローカル');await p.evaluate(h=>location.hash=h,hash({...draft,t:'共有'}));await p.waitForTimeout(30);await p.locator('#title').fill('共有を編集');await p.evaluate(()=>location.hash='');await p.waitForTimeout(30);assert.equal(await p.locator('#title').inputValue(),'ローカル');await p.goBack();assert.equal(await p.locator('#title').inputValue(),'共有');await p.goForward();assert.equal(await p.locator('#title').inputValue(),'ローカル');await p.evaluate(()=>{const s=document.createElement('script');s.textContent='window.badScript=true';document.body.append(s);});assert.equal(await p.evaluate(()=>window.badScript),undefined);});
test('named save and reload restore ranking while photos stay browser-local across shares',async t=>{
 const p=await pageFor(t);await importFile(p,await raster(p));const savedPhoto=await photo(p);
 await p.locator('#title').fill('保存したランキング');await p.locator('#save').click();const id=await p.locator('#saved').inputValue();
 await p.locator('.rank-row').nth(1).locator('[data-action=up]').click();await p.locator('#title').fill('編集後');await p.reload();
 assert.equal(await p.locator('#title').inputValue(),'編集後');assert.equal(await p.locator('.rank-name').first().textContent(),'小川彩');
 p.on('dialog',d=>d.accept());await p.locator('#saved').selectOption(id);await p.locator('#load').click();
 assert.equal(await p.locator('#title').inputValue(),'保存したランキング');assert.equal(await p.locator('.rank-name').first().textContent(),'井上和');assert.equal(await photo(p),savedPhoto);
 const link=await p.evaluate(()=>shareURL());await p.locator('#title').fill('共有前の下書き');await p.goto(link);await p.locator('#title').fill('共有だけ編集');
 await p.evaluate(()=>location.hash='');await p.waitForFunction(()=>!shared);assert.equal(await p.locator('#title').inputValue(),'共有前の下書き');await p.reload();assert.equal(await p.locator('#title').inputValue(),'共有前の下書き');
});
test('three consecutive PNG exports refresh snapshot and release old object URLs',async t=>{
 const p=await pageFor(t);await importFile(p,await raster(p));
 await p.evaluate(()=>{window.revoked=[];const revoke=URL.revokeObjectURL;URL.revokeObjectURL=function(url){revoked.push(url);return revoke.call(URL,url);};});
 let previous;
 for(let i=0;i<3;i++){
  await p.locator('#title').fill('連続出力 '+i);await p.locator('#png').click();await p.locator('#export-dialog[open]').waitFor();
  await p.locator('#export-image').evaluate(img=>img.decode());const current=await p.locator('#export-image').getAttribute('src');assert.notEqual(current,previous);
  assert.equal(await p.evaluate(()=>exportTitle),'連続出力 '+i);assert.equal(await p.locator('#png').getAttribute('aria-busy'),null);
  if(previous)assert.ok((await p.evaluate(()=>revoked)).includes(previous));previous=current;
  await p.keyboard.press('Escape');await p.locator('#export-dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement.id==='png');assert.equal(await p.evaluate(()=>document.activeElement.id),'png');assert.equal(await p.locator('#png').isDisabled(),false);
 }
});
