import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {validateData,validateSnapshot,viewRelease,compareRelease,predict,predictionAccuracy,csv,safeUrl,time} from '../meet-greet/core.mjs';
import {createDemo} from '../meet-greet/demo.mjs';
import {parsePost,importSnapshot,collectX} from '../scripts/meet-greet.mjs';
const demo=()=>createDemo();
const current=d=>d.releases.find(r=>r.id==='demo-current');
const report=(r,i,extra={})=>({releaseId:r.id,round:3,slotId:'demo-B-3',postId:String(i),authorKey:`a${i}`,postedAt:r.rounds[2].resultsAt,accepted:true,basis:'round_total',applied:10,won:0,...extra});
const post=(r,text)=>({id:'100',author_id:'200',created_at:r.rounds[2].resultsAt,text:text||'DEMO-demo-current オンライン ミーグリ 第3次 サンプルB 11/08 第1部 応募合計10枚 当選1枚'});
test('empty production dataset is valid and not synthetic results',async()=>{const d=JSON.parse(await fs.readFile(new URL('../v1/meet-greet.json',import.meta.url)));assert.deepEqual(d,{schemaVersion:1,generatedAt:null,releases:[]});});
test('synthetic fixture validates',()=>assert.equal(validateData(demo()).demo,true));
test('round 2 opening confirms round 1, never round 2',()=>{const r=current(demo());assert.equal(viewRelease(r,1).members[0].sold,2);assert.equal(viewRelease(r,2).members[0].sold,4);});
test('as-of view excludes later observations',()=>{const r=current(demo());assert.equal(viewRelease(r,2,Date.parse(r.rounds[1].opensAt)).members[0].sold,2);});
test('prior availability becomes unknown; sold-out survives until reopening',()=>{const v=viewRelease(current(demo()),3);assert.equal(v.cells.find(c=>c.id==='demo-A-1').status,'sold_out');assert.equal(v.cells.find(c=>c.id==='demo-C-2').status,'unknown');});
test('new official availability overrides an earlier sell-out and prediction',()=>{const r=current(demo());r.officialSnapshots[1].cells.find(c=>c.slotId==='demo-A-1').status='available';const c=viewRelease(r,2).cells.find(c=>c.id==='demo-A-1');assert.equal(c.status,'available');assert.equal(c.predicted,null);assert.equal(c.firstConfirmedRound,null);});
test('exempt and cancelled are excluded from denominator; closed is not sold-out',()=>{const r=current(demo());const s=r.officialSnapshots[1];s.cells.find(c=>c.slotId==='demo-C-1').status='cancelled';s.cells.find(c=>c.slotId==='demo-C-2').status='closed';const m=viewRelease(r,2).members[2];assert.equal(m.total,2);assert.equal(m.sold,0);assert.equal(m.complete,false);});
test('a missing cell is not sold-out',()=>{const r=current(demo());r.officialSnapshots[1].cells=r.officialSnapshots[1].cells.filter(c=>c.slotId!=='demo-C-2');r.officialSnapshots[1].complete=false;assert.equal(viewRelease(r,2).cells.find(c=>c.id==='demo-C-2').status,'unknown');});
test('closed reception is rejected',()=>{const r=current(demo()),s=structuredClone(r.officialSnapshots[1]);s.receptionOpen=false;assert.throws(()=>validateSnapshot(r,s),/Closed reception/);});
test('pre-open, after-close and future snapshots rejected',()=>{const r=current(demo()),s=structuredClone(r.officialSnapshots[1]);s.observedAt='2026-09-16T13:59:59+09:00';assert.throws(()=>validateSnapshot(r,s),/window/);s.observedAt=r.rounds[2].closesAt;assert.throws(()=>validateSnapshot(r,s),/window/);s.observedAt=r.rounds[2].opensAt;assert.throws(()=>validateSnapshot(r,s,Date.parse('2026-09-01T00:00:00Z')),/window/);});
test('incomplete official snapshots cannot claim completeness',()=>{const r=current(demo()),s=structuredClone(r.officialSnapshots[1]);s.cells.pop();assert.throws(()=>validateSnapshot(r,s),/Incomplete/);});
test('unsafe and unofficial source URLs rejected',()=>{for(const url of ['javascript:alert(1)','https://fortunemusic.jp.evil.test/','http://fortunemusic.jp/','https://a:b@fortunemusic.jp/'])assert.equal(safeUrl(url,true),null);});
test('duplicate slots and invalid dates rejected',()=>{let d=demo(),r=current(d);r.slots.push({...r.slots[0],id:'other'});assert.throws(()=>validateData(d),/Duplicate member/);d=demo();current(d).slots[0].date='2026-02-30';assert.throws(()=>validateData(d),/Invalid date/);});
test('timezone is mandatory',()=>assert.throws(()=>time('2026-09-18T12:00:00'),/Timezone/));
test('newly-added slots do not change historical denominators',()=>{const r=current(demo());r.slots.push({...r.slots[0],id:'added',session:9,firstRound:3});assert.equal(viewRelease(r,2).members[0].total,4);assert.equal(viewRelease(r,3).members[0].total,5);});
test('comparison uses same round and stable member IDs',()=>{const d=demo(),r=current(d),m=compareRelease(d,r,2)[0];assert.equal(m.sold,4);assert.equal(m.previous.sold,3);assert.equal(m.delta,1);assert.equal(m.deltaPp,25);});
test('unconfirmed comparison is null rather than zero',()=>{const d=demo();assert.equal(compareRelease(d,current(d),3)[1].delta,null);});
test('cross-group and cross-format comparison rejected',()=>{const d=demo();d.releases[0].eventType='real';assert.throws(()=>validateData(d),/Previous release/);});
test('denominator difference is marked',()=>{const d=demo();current(d).officialSnapshots[1].cells.find(c=>c.slotId==='demo-C-1').status='exempt';assert.equal(compareRelease(d,current(d),2)[2].denominatorChanged,true);});
test('one loss report cannot produce a sell-out prediction',()=>{const r=current(demo()),p=predict(r,[report(r,1)],3,r.rounds[2].resultsAt);assert.equal(p.cells.find(c=>c.slotId==='demo-B-3').label,'insufficient');});
test('three distinct account losses produce a heuristic, never official status',()=>{const r=current(demo());r.predictions=[predict(r,[1,2,3].map(i=>report(r,i)),3,r.rounds[2].resultsAt)];const c=viewRelease(r,3).cells.find(c=>c.id==='demo-B-3');assert.equal(c.predicted,'likely');assert.equal(c.status,'unknown');});
test('same account repeated reports count once; newest total wins',()=>{const r=current(demo()),reports=[report(r,1),report(r,2,{authorKey:'a1',postedAt:'2026-09-17T18:01:00+09:00',won:10})];const c=predict(r,reports,3,'2026-09-17T18:02:00+09:00').cells.find(c=>c.slotId==='demo-B-3');assert.equal(c.authors,1);assert.equal(c.won,10);assert.equal(c.label,'insufficient');});
test('other releases, rounds, unreviewed and future reports excluded',()=>{const r=current(demo());const bad=[report(r,1,{releaseId:'other'}),report(r,2,{round:2}),report(r,3,{accepted:false}),report(r,4,{postedAt:'2026-09-20T00:00:00Z'}),report(r,5,{won:11}),report(r,6,{basis:'per_order'})];assert.equal(predict(r,bad,3,r.rounds[2].resultsAt).cells.find(c=>c.slotId==='demo-B-3').authors,0);});
test('post-confirmation prediction generation rejected',()=>{const r=current(demo());assert.throws(()=>predict(r,[],2,r.rounds[2].opensAt),/window/);});
test('prediction history retained when official results arrive',()=>{const r=current(demo());assert.equal(r.predictions.length,2);assert.equal(viewRelease(r,2).cells.find(c=>c.id==='demo-A-3').predicted,null);assert.ok(predictionAccuracy(r,2).judged>0);assert.equal(r.predictions.length,2);});
test('CSV neutralizes formulas and quotes fields',()=>{const output=csv([['=SUM(A1:A2)','+1','@x','safe,"quoted"']]);assert.ok(output.includes("'=SUM"));assert.ok(output.includes("'+1"));assert.ok(output.includes('""quoted""'));});
test('strict parser maps explicit totals and hashes account IDs',()=>{const r=current(demo()),p=parsePost(post(r),r,3,'a'.repeat(32));assert.equal(p.accepted,true);assert.equal(p.slotId,'demo-B-3');assert.equal(p.applied,10);assert.equal(p.won,1);assert.match(p.authorKey,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(p).includes('author_id'));});
test('retweets/quotes, ambiguous counts, wrong format and multi-member posts queued',()=>{const r=current(demo());assert.equal(parsePost({...post(r),referenced_posts:[{type:'quoted'}]},r,3,'salt').accepted,false);for(const text of [post(r).text.replace('応募合計10枚 当選1枚','1/10'),post(r).text.replace('オンライン','リアル'),post(r).text+' サンプルC',post(r).text+' 予想',post(r).text.replace('第3次','第2次')])assert.equal(parsePost(post(r,text),r,3,'salt').accepted,false);});
test('official import requires review and preserves immutable history',()=>{const d=demo(),r=current(d),s={...r.officialSnapshots[1],id:'correction',reviewed:true};const updated=importSnapshot(d,r.id,s,Buffer.from('verified source'));assert.equal(current(updated).officialSnapshots.length,3);assert.equal(r.officialSnapshots.length,2);assert.throws(()=>importSnapshot(d,r.id,{...s,reviewed:false},Buffer.from('x')),/reviewed/);assert.throws(()=>importSnapshot(updated,r.id,s,Buffer.from('changed')),/conflict/);assert.equal(current(importSnapshot(updated,r.id,s,Buffer.from('verified source'))).officialSnapshots.length,3);});
test('collector resumes capped pagination without skipping or premature publication',async()=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'meet-greet-'));
  const dataPath=path.join(dir,'data.json'),privateDir=path.join(dir,'private');
  const originalNow=Date.now,oldToken=process.env.X_BEARER_TOKEN,oldSalt=process.env.MEET_GREET_AUTHOR_SALT;
  let now=Date.parse('2026-09-18T12:00:00Z');Date.now=()=>now;
  process.env.X_BEARER_TOKEN='test-only';process.env.MEET_GREET_AUTHOR_SALT='test-only-'.repeat(4);
  try{
    const d=demo(),r=current(d);await fs.writeFile(dataPath,JSON.stringify(d));let calls=0;
    const mock=async url=>{const u=new URL(url);calls++;assert.equal(u.searchParams.get('start_time'),r.rounds[2].resultsAt);if(calls===1){assert.equal(u.searchParams.has('next_token'),false);return {ok:true,json:async()=>({data:[post(r)],meta:{next_token:'next-page'}})};}assert.equal(u.searchParams.get('next_token'),'next-page');return {ok:true,json:async()=>({data:[],meta:{result_count:0}})};};
    const first=await collectX(dataPath,r.id,3,privateDir,1,mock);assert.equal(first.pending,true);assert.equal(current(await readJson(dataPath)).predictions.length,2);
    assert.equal((await collectX(dataPath,r.id,3,privateDir,1,mock)).skipped,'cooldown');
    now+=16*60000;const second=await collectX(dataPath,r.id,3,privateDir,1,mock);assert.equal(second.published,true);assert.equal(calls,2);assert.equal(current(await readJson(dataPath)).predictions.length,3);
    const published=await fs.readFile(dataPath,'utf8');assert.ok(!published.includes('authorKey'));assert.ok(!published.includes('postId'));assert.ok(!published.includes('test-only'));
  }finally{Date.now=originalNow;if(oldToken===undefined)delete process.env.X_BEARER_TOKEN;else process.env.X_BEARER_TOKEN=oldToken;if(oldSalt===undefined)delete process.env.MEET_GREET_AUTHOR_SALT;else process.env.MEET_GREET_AUTHOR_SALT=oldSalt;await fs.rm(dir,{recursive:true,force:true});}
});
async function readJson(p){return JSON.parse(await fs.readFile(p,'utf8'));}
test('already-confirmed sell-outs are not counted as successful new predictions',()=>{const r=current(demo());const p=predict(r,[1,2,3].map(i=>report(r,i,{slotId:'demo-A-1'})),3,r.rounds[2].resultsAt);assert.equal(p.cells.find(c=>c.slotId==='demo-A-1').label,'insufficient');});
test('publisher rejects stale input without overwriting newer data',async()=>{const {publish}=await import('../scripts/meet-greet.mjs');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mg-conflict-'));const file=path.join(dir,'data.json');try{await fs.writeFile(file,JSON.stringify({newer:true}));await assert.rejects(publish(file,{older:true},'bad-hash'),/conflict/);assert.deepEqual(await readJson(file),{newer:true});}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('navigation installer preserves changing bundle names and is idempotent',async()=>{const {installNavigation}=await import('../scripts/install-meet-greet-nav.mjs');const html='<html><head></head><body><div id="root"></div><script src="current-hash.js"></script></body></html>';const result=installNavigation(html);assert.ok(result.includes('current-hash.js'));assert.ok(result.includes('./meet-greet/'));assert.equal(installNavigation(result),result);assert.throws(()=>installNavigation('<html/>'),/Unknown Expo/);});
