// Run: node --test tests/senbatsu.test.cjs (requires Playwright + Chromium).
const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const {createHash}=require('node:crypto');
const {chromium}=require('playwright');
const html=fs.readFileSync(process.env.SENBATSU_HTML||'senbatsu/index.html','utf8');
const KEY='zaka-senbatsu-v1';
const draft={v:1,t:'自分の下書き',r:[[['井上和','n'],null,null],[null],[null]]};
const shared={v:1,t:'友達の選抜',r:[[['小川彩','n']],[null,null],[]]};
const hash=s=>'#s='+Buffer.from(JSON.stringify(s)).toString('base64url');
let browser,server,origin;
before(async()=>{server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});});
after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
async function pageFor(t,{fragment='',seed=draft,blocked=false}={}){const context=await browser.newContext();t.after(()=>context.close());await context.addInitScript(({key,seed,blocked})=>{if(seed&&!sessionStorage.getItem('seeded')){localStorage.setItem(key,JSON.stringify(seed));sessionStorage.setItem('seeded','yes');}if(blocked)Storage.prototype.setItem=()=>{throw Error('Storage blocked');};},{key:KEY,seed,blocked});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.goto(origin+'/'+fragment);await page.locator('#count').waitFor();return page;}
async function navigateHash(page,value){await page.evaluate(value=>{location.hash=value;},value);await page.waitForTimeout(30);}
async function title(page){return page.locator('#title').inputValue();}
test('inline CSP matches the exact script bytes',()=>{const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];const digest=createHash('sha256').update(script).digest('base64');assert.ok(html.includes("script-src 'sha256-"+digest+"'"));});
test('clearing a share restores the draft, resets undo and enables autosave',async t=>{const page=await pageFor(t,{fragment:hash(shared)});assert.equal(await title(page),shared.t);await page.locator('#title').fill('共有だけを編集');await page.locator('.member').first().click();assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).t,KEY),draft.t);await navigateHash(page,'');assert.equal(await title(page),draft.t);assert.equal(await page.locator('#undo').isDisabled(),true);assert.equal(await page.locator('.slot[aria-pressed=true]').count(),0);assert.match(await page.locator('#storage-status').textContent(),/自動保存/);await page.locator('#title').fill('復帰後の下書き');await page.reload();assert.equal(await title(page),'復帰後の下書き');});
test('back/forward and multiple shares keep the same local draft',async t=>{const page=await pageFor(t);await page.locator('#title').fill('直前の編集');await navigateHash(page,hash(shared));await navigateHash(page,hash({...shared,t:'別の共有'}));await navigateHash(page,'');assert.equal(await title(page),'直前の編集');await page.goBack();assert.equal(await title(page),'別の共有');await page.goBack();assert.equal(await title(page),shared.t);await page.goBack();assert.equal(await title(page),'直前の編集');await page.goForward();assert.equal(await title(page),shared.t);});
test('invalid shared fragments preserve current state and draft isolation',async t=>{const page=await pageFor(t,{fragment:hash(shared)});await navigateHash(page,'#s=invalid');assert.equal(await title(page),shared.t);assert.match(await page.locator('#toast').textContent(),/読み込めません/);await page.locator('#title').fill('壊れたリンク後');assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).t,KEY),draft.t);await navigateHash(page,'#other');assert.equal(await title(page),draft.t);});
test('no saved draft restores the blank default after leaving a share',async t=>{const page=await pageFor(t,{fragment:hash(shared),seed:null});await navigateHash(page,'');assert.equal(await title(page),'わたしの坂道選抜');assert.equal(await page.locator('#count').textContent(),'0 / 21人');});
test('in-memory draft survives shared navigation even when writes fail',async t=>{const page=await pageFor(t,{blocked:true});await page.locator('#title').fill('保存できない下書き');await navigateHash(page,hash(shared));await navigateHash(page,'');assert.equal(await title(page),'保存できない下書き');assert.match(await page.locator('#storage-status').textContent(),/利用できません/);});
test('export snapshots title, names, count and centers; blocks repeats across rerender',async t=>{const page=await pageFor(t);await page.evaluate(()=>{window.drawn=[];window.blobCalls=0;const draw=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...rest){drawn.push(text);return draw.call(this,text,...rest);};Object.defineProperty(document.fonts,'ready',{value:new Promise(r=>window.releaseFonts=r)});const blob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){blobCalls++;blob.call(this,b=>{window.releaseBlob=()=>cb(b);},...args);};Object.defineProperty(navigator,'canShare',{value:()=>true});Object.defineProperty(navigator,'share',{value:async data=>window.sharedTitle=data.title});});await page.locator('#png').click();assert.equal(await page.locator('#png').getAttribute('aria-busy'),'true');await page.locator('#title').fill('あとから変更');await page.locator('#preset').selectOption('5,5,6');assert.equal(await page.locator('#png').isDisabled(),true);await page.evaluate(()=>{$('png').onclick();releaseFonts();});await page.waitForFunction(()=>!!window.releaseBlob);assert.equal(await page.evaluate(()=>blobCalls),1);const drawn=await page.evaluate(()=>drawn);assert.ok(drawn.includes(draft.t));assert.ok(drawn.includes('井上和'));assert.ok(drawn.includes('1人の、わたしだけの選抜'));assert.equal(drawn.filter(x=>x==='CENTER').length,1);assert.ok(!drawn.includes('あとから変更'));await page.locator('#title').fill('画像作成中にもう一度変更');await page.evaluate(()=>releaseBlob());await page.locator('#export-dialog[open]').waitFor();assert.equal(await page.locator('#png').getAttribute('aria-busy'),null);await page.locator('#share-image').click();assert.equal(await page.evaluate(()=>sharedTitle),draft.t);const size=await page.locator('#export-image').evaluate(async img=>{await img.decode();return {width:img.naturalWidth,height:img.naturalHeight};});assert.deepEqual(size,{width:1560,height:1060});await page.locator('[data-close="export-dialog"]').click();assert.equal(await page.locator('#png').isDisabled(),false);});
test('failed export clears busy state and permits a successful retry',async t=>{const page=await pageFor(t);await page.evaluate(()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){HTMLCanvasElement.prototype.toBlob=original;cb(null);};});await page.locator('#png').click();await page.waitForFunction(()=>!document.getElementById('png').disabled);assert.match(await page.locator('#toast').textContent(),/作成できません/);assert.equal(await page.locator('#png').textContent(),'画像を保存');assert.equal(await page.locator('#png').getAttribute('aria-busy'),null);await page.locator('#png').click();await page.locator('#export-dialog[open]').waitFor();});
test('empty selection cannot start export',async t=>{const page=await pageFor(t,{seed:null});assert.equal(await page.locator('#png').isDisabled(),true);await page.evaluate(()=>$('png').onclick());assert.equal(await page.locator('#export-dialog[open]').count(),0);});
test('mobile and desktop viewport do not overflow',async t=>{const page=await pageFor(t);for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}});
test('CSP rejects an unapproved inline script',async t=>{const page=await pageFor(t);await page.evaluate(()=>{const script=document.createElement('script');script.textContent='window.unapprovedScriptRan=true';document.body.append(script);});assert.equal(await page.evaluate(()=>window.unapprovedScriptRan),undefined);});
