// Dependency-free regression tests executing the production inline script in a VM.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {createHash}=require('node:crypto');
const html=fs.readFileSync(process.env.SENBATSU_HTML||'senbatsu/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const KEY='zaka-senbatsu-v1';
const draft={v:1,t:'自分の下書き',r:[[['井上和','n'],null,null],[null],[null]]};
const shared={v:1,t:'友達の選抜',r:[[['小川彩','n']],[null,null],[]]};
const fragment=s=>'#s='+Buffer.from(JSON.stringify(s)).toString('base64url');
function app({seed=draft,hash='',blocked=false}={}){
 const elements=new Map(),storage=new Map(seed?[[KEY,JSON.stringify(seed)]]:[]),drawn=[],listeners={};let blobs=0,modalCount=0;
 class Element{constructor(){this.value='';this.textContent='';this.children=[];this.dataset={};this.style={};this.attributes={};this.classList={contains:()=>false};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}querySelector(){return null;}focus(){}select(){}showModal(){this.open=true;modalCount++;}close(){this.open=false;}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
 const ctx=new Proxy({fillText:text=>drawn.push(text),measureText:t=>({width:t.length*12})},{get:(o,k)=>k in o?o[k]:()=>{}});
 const sandbox={console,TextEncoder,TextDecoder,Uint8Array,setTimeout:()=>0,clearTimeout:()=>{},atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),confirm:()=>true,location:{hash,origin:'https://test.invalid',pathname:'/senbatsu/'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('disabled');storage.set(k,v);}},URL:{createObjectURL:()=> 'blob:export',revokeObjectURL:()=>{}},File:class{constructor(parts,name,options){Object.assign(this,{parts,name,...options});}},navigator:{canShare:()=>true,share:async data=>{sandbox.shareData=data;}},document:{getElementById:get,querySelectorAll:()=>[],fonts:{ready:Promise.resolve()},createElement:tag=>{const el=new Element();if(tag==='canvas'){el.getContext=()=>ctx;el.toBlob=cb=>{blobs++;sandbox.blobCallback=cb;if(!sandbox.delayBlob)cb(sandbox.failBlob?null:{png:true});};}return el;}},window:{addEventListener:(event,fn)=>listeners[event]=fn}};
 const context=vm.createContext(sandbox);vm.runInContext(script,context);
 return{get,storage,drawn,sandbox,run:code=>vm.runInContext(code,context),get blobs(){return blobs;},get modals(){return modalCount;},navigate:hash=>{sandbox.location.hash=hash;listeners.hashchange();}};
}
test('CSP hash matches exact production script',()=>{assert.ok(html.includes("script-src 'sha256-"+createHash('sha256').update(script).digest('base64')+"'"));new vm.Script(script);});
test('clear hash restores original draft and resets edit mode, selected seat and undo',()=>{const a=app({hash:fragment(shared)});a.run("change(()=>state.t='shared edit');selected=[0,0]");assert.equal(JSON.parse(a.storage.get(KEY)).t,draft.t);a.navigate('');assert.equal(a.run('state.t'),draft.t);assert.equal(a.run('shared'),false);assert.equal(a.run('selected'),null);assert.equal(a.run('history.length'),0);a.run("state.t='new draft';persist()");assert.equal(JSON.parse(a.storage.get(KEY)).t,'new draft');});
test('repeated share navigation and back/forward equivalent transitions preserve latest draft',()=>{const a=app();a.run("state.t='latest draft';persist()");for(const h of [fragment(shared),fragment({...shared,t:'second'}),'',fragment(shared),''])a.navigate(h);assert.equal(a.run('state.t'),'latest draft');});
test('invalid share retains current state and never writes shared edits into local draft',()=>{const a=app({hash:fragment(shared)});a.navigate('#s=invalid');assert.equal(a.run('state.t'),shared.t);assert.equal(a.run('shared'),true);a.run("state.t='edit';persist()");assert.equal(JSON.parse(a.storage.get(KEY)).t,draft.t);a.navigate('#other');assert.equal(a.run('state.t'),draft.t);});
test('leaving share without local draft restores default empty formation',()=>{const a=app({seed:null,hash:fragment(shared)});a.navigate('');assert.equal(a.run('filled()'),0);assert.equal(a.run('state.r.flat().length'),21);});
test('storage failure does not lose the in-memory draft on share navigation',()=>{const a=app({blocked:true});a.run("state.t='unsaved';persist()");a.navigate(fragment(shared));a.navigate('');assert.equal(a.run('state.t'),'unsaved');assert.equal(a.run('storageError'),true);});
test('PNG snapshot is stable through fonts/blob awaits and native share uses its title',async()=>{const a=app();let release;a.sandbox.document.fonts.ready=new Promise(r=>release=r);a.sandbox.delayBlob=true;const pending=a.run('makePNG()');assert.equal(a.get('png').attributes['aria-busy'],'true');a.run("state.t='edited';state.r=[[['小川彩','n'],['遠藤さくら','n']],[],[]];render()");assert.equal(a.get('png').disabled,true);await a.run('makePNG()');release();await Promise.resolve();await Promise.resolve();assert.equal(a.blobs,1);assert.ok(a.drawn.includes(draft.t));assert.ok(a.drawn.includes('井上和'));assert.ok(a.drawn.includes('1人の、わたしだけの選抜'));assert.ok(!a.drawn.includes('2人の、わたしだけの選抜'));assert.ok(!a.drawn.includes('小川彩'));assert.equal(a.drawn.filter(t=>t==='CENTER').length,1);a.run("state.t='edited again'");a.sandbox.blobCallback({png:true});await pending;assert.equal(a.modals,1);assert.equal(a.get('png').attributes['aria-busy'],undefined);assert.equal(a.get('png').disabled,false);await a.get('share-image').onclick();assert.equal(a.sandbox.shareData.title,draft.t);});
test('failed PNG releases busy state and permits successful retry',async()=>{const a=app();a.sandbox.failBlob=true;await a.run('makePNG()');assert.equal(a.get('png').disabled,false);assert.equal(a.get('png').attributes['aria-busy'],undefined);assert.match(a.get('toast').textContent,/作成できません/);a.sandbox.failBlob=false;await a.run('makePNG()');assert.equal(a.modals,1);});
test('empty formation does not create a PNG',async()=>{const a=app({seed:null});await a.run('makePNG()');assert.equal(a.blobs,0);assert.equal(a.modals,0);});
